from sqlite_rs._sqlite3 import Connection as Connection
from sqlite_rs._sqlite3 import connect as connect

def sum_as_string(a: int, b: int) -> str: ...
def query_via_rust(connection: Connection, sql: str) -> list[list[object]]: ...
