import ctypes
from pathlib import Path
from typing import Protocol

import sqlite_rs.sqlite3

# The bundled SQLite that this package, sqlite_rs.sqlite3 and any ctypes caller
# all link, e.g. ctypes.CDLL(str(LIBSQLITE3_PATH)).
LIBSQLITE3_PATH: Path

# True when the extension was built without optimization, which costs roughly
# 3x on a large fetch. Only the benchmark script reads it.
DEBUG_BUILD: bool

# Rows in each chunk of a result column.
CHUNK_ROWS: int

class ArrowScalar(Protocol):
    def as_py(self) -> object: ...

# One column, as a run of Arrow chunks. Anything speaking the PyCapsule
# protocol -- pyarrow, polars, duckdb, arro3 -- consumes these without a copy,
# and sqlite_rs needs no Arrow package of its own installed to produce them.
# The capsules are opaque PyCapsule objects with no public type.
class ArrowChunkedArray(Protocol):
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
    def __arrow_c_schema__(self) -> object: ...
    def __len__(self) -> int: ...
    def __getitem__(self, i: int) -> ArrowScalar: ...
    @property
    def num_chunks(self) -> int: ...

# Every column at once. Whole-table consumers -- polars' DataFrame, pyarrow's
# table -- take this in a single call.
class ArrowTable(Protocol):
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
    def __arrow_c_schema__(self) -> object: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def column_names(self) -> list[str]: ...

# One chunked array per column. Docstrings live on the functions themselves
# (PYI021): help() reads them from _core.
def execute_and_fetch_all(
    connection: sqlite_rs.sqlite3.Connection, sql: str
) -> list[ArrowChunkedArray]: ...
def fetch_all(cursor: sqlite_rs.sqlite3.Cursor) -> list[ArrowChunkedArray]: ...
def execute_and_fetch_table(
    connection: sqlite_rs.sqlite3.Connection, sql: str
) -> ArrowTable: ...
def fetch_table(cursor: sqlite_rs.sqlite3.Cursor) -> ArrowTable: ...
def get_raw_db_ptr(connection: sqlite_rs.sqlite3.Connection) -> ctypes.c_void_p: ...
def get_raw_stmt_ptr(cursor: sqlite_rs.sqlite3.Cursor) -> ctypes.c_void_p: ...
def execute_and_fetch_all_via_raw_pointer(
    db_ptr: int | ctypes.c_void_p, sql: str
) -> list[ArrowChunkedArray]: ...
def fetch_all_via_raw_pointer(
    stmt_ptr: int | ctypes.c_void_p,
) -> list[ArrowChunkedArray]: ...
def execute_and_fetch_table_via_raw_pointer(
    db_ptr: int | ctypes.c_void_p, sql: str
) -> ArrowTable: ...
def fetch_table_via_raw_pointer(
    stmt_ptr: int | ctypes.c_void_p,
) -> ArrowTable: ...
